### ISSUE TITLE
FileNotFoundError when using SAM on local files

### ISSUE THREAD

**Issue by ejboomus** [HumanSignal/label-studio-ml-backend#443]
**Describe the bug**

FileNotFoundError is thrown when trying to annotate images that are local files and were uploaded using json. The images can be seen online and are also able to be interacted with on label studio, just not with the SAM model. However, SAM model works with images that are imported using the GUI. 

Document root path: /home/user/LABELSTUDIODATA/
Local path: /home/user/LABELSTUDIODATA/images
Image can be found at:  http://host:4040/data/local-files/?d=images/from_dashapp/full_seg94.png

**Details**
- Running through SSH
- Pictures are uploaded through requests.POST (which works)
- Pictures can be seen and annotated
- SAM model throws error when attempting to annotate with it on local files
- I have local files set up through "Source Cloud Storage"
- SAM model does not throw error when annotating images that were imported using GUI

samserver    | [2024-03-06 22:25:57,095] [DEBUG] [sam_predictor::set_image::83] Payload not found for /data/local-files/?d=images/from_dashapp/full_seg94.png in `IN_MEM_CACHE`: calculating from scratch
samserver    | [2024-03-06 22:25:57,099] [ERROR] [label_studio_ml.exceptions::exception_f::53] Traceback (most recent call last):
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
samserver    |     return f(*args, **kwargs)
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 66, in _predict
samserver    |     response = model.predict(tasks, context=context, **params)
samserver    |   File "/app/model.py", line 48, in predict
samserver    |     predictor_results = PREDICTOR.predict(
samserver    |   File "/app/sam_predictor.py", line 196, in predict
samserver    |     return self.predict_sam(img_path, point_coords, point_labels, input_box)
samserver    |   File "/app/sam_predictor.py", line 168, in predict_sam
samserver    |     self.set_image(img_path, calculate_embeddings=False)
samserver    |   File "/app/sam_predictor.py", line 84, in set_image
samserver    |     image_path = get_image_local_path(
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/utils.py", line 67, in get_image_local_path
samserver    |     image_local_path = get_local_path(
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py", line 68, in get_local_path
samserver    |     raise FileNotFoundError(filepath)
samserver    | FileNotFoundError: /images/from_dashapp/full_seg94.png
samserver    |
samserver    | Traceback (most recent call last):
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py", line 39, in exception_f
samserver    |     return f(*args, **kwargs)
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py", line 66, in _predict
samserver    |     response = model.predict(tasks, context=context, **params)
samserver    |   File "/app/model.py", line 48, in predict
samserver    |     predictor_results = PREDICTOR.predict(
samserver    |   File "/app/sam_predictor.py", line 196, in predict
samserver    |     return self.predict_sam(img_path, point_coords, point_labels, input_box)
samserver    |   File "/app/sam_predictor.py", line 168, in predict_sam
samserver    |     self.set_image(img_path, calculate_embeddings=False)
samserver    |   File "/app/sam_predictor.py", line 84, in set_image
samserver    |     image_path = get_image_local_path(
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_ml/utils.py", line 67, in get_image_local_path
samserver    |     image_local_path = get_local_path(
samserver    |   File "/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py", line 68, in get_local_path
samserver    |     raise FileNotFoundError(filepath)
samserver    | FileNotFoundError: /images/from_dashapp/full_seg94.png
samserver    |
samserver    | [2024-03-06 22:25:57,105] [DEBUG] [label_studio_ml.api::log_response_info::181] Response status: 500 INTERNAL SERVER ERROR
samserver    | [2024-03-06 22:25:57,106] [DEBUG] [label_studio_ml.api::log_response_info::182] Response headers: Content-Type: application/json
samserver    | Content-Length: 1253
samserver    |
samserver    |
samserver    | [2024-03-06 22:25:57,106] [DEBUG] [label_studio_ml.api::log_response_info::183] Response body: b'{"detail":"FileNotFoundError: /images/from_dashapp/full_seg94.png","request":{},"result":{"traceback":"Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py\\", line 39, in exception_f\\n    return f(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py\\", line 66, in _predict\\n    response = model.predict(tasks, context=context, **params)\\n  File \\"/app/model.py\\", line 48, in predict\\n    predictor_results = PREDICTOR.predict(\\n  File \\"/app/sam_predictor.py\\", line 196, in predict\\n    return self.predict_sam(img_path, point_coords, point_labels, input_box)\\n  File \\"/app/sam_predictor.py\\", line 168, in predict_sam\\n    self.set_image(img_path, calculate_embeddings=False)\\n  File \\"/app/sam_predictor.py\\", line 84, in set_image\\n    image_path = get_image_local_path(\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/utils.py\\", line 67, in get_image_local_path\\n    image_local_path = get_local_path(\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py\\", line 68, in get_local_path\\n    raise FileNotFoundError(filepath)\\nFileNotFoundError: /images/from_dashapp/full_seg94.png\\n"},"status":500}\n'

**Comment by niklub** [comment]
Hello! Have you tried to setup local file serving like in https://github.com/HumanSignal/label-studio-ml-backend/tree/master/label_studio_ml/examples/segment_anything_model#enabling-local-storage-file-serving ?

Specifically, you can try passing
```
LOCAL_FILES_DOCUMENT_ROOT=/home/user/LABELSTUDIODATA/
```
while initializing SAM backend with environmental variables

**Comment by scfrank** [comment]
I am having a similar problem just replicating the SAM tutorial here:
https://labelstud.io/blog/get-started-using-segment-anything/
with files uploaded with the file uploader (as in the tutorial)

```
segment_anything_model  | [2024-04-25 15:59:36,365] [DEBUG] [label_studio_ml.api::log_response_info::187] Response body: b'{"detail":"MissingSchema: Invalid URL \'10.179.18.196/data/upload/1/50b124ab-0002.jpg\': No scheme supplied. Perhaps you meant https://10.179.18.196/data/upload/1/50b124ab-0002.jpg?","request":{},"result":{"traceback":"Traceback (most recent call last):\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/exceptions.py\\", line 39, in exception_f\\n    return f(*args, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_ml/api.py\\", line 69, in _predict\\n    response = model.predict(tasks, context=context, **params)\\n  File \\"/app/model.py\\", line 51, in predict\\n    predictor_results = PREDICTOR.predict(\\n  File \\"/app/sam_predictor.py\\", line 202, in predict\\n    return self.predict_sam(img_path, point_coords, point_labels, input_box, task)\\n  File \\"/app/sam_predictor.py\\", line 173, in predict_sam\\n    self.set_image(img_path, calculate_embeddings=False, task=task)\\n  File \\"/app/sam_predictor.py\\", line 86, in set_image\\n    image_path = get_local_path(\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py\\", line 143, in get_local_path\\n    filepath = download_and_cache(\\n  File \\"/usr/local/lib/python3.8/site-packages/label_studio_tools/core/utils/io.py\\", line 183, in download_and_cache\\n    r = requests.get(url, stream=True, headers=headers)\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/api.py\\", line 73, in get\\n    return request(\\"get\\", url, params=params, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/api.py\\", line 59, in request\\n    return session.request(method=method, url=url, **kwargs)\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/sessions.py\\", line 575, in request\\n    prep = self.prepare_request(req)\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/sessions.py\\", line 486, in prepare_request\\n    p.prepare(\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/models.py\\", line 368, in prepare\\n    self.prepare_url(url, params)\\n  File \\"/usr/local/lib/python3.8/site-packages/requests/models.py\\", line 439, in prepare_url\\n    raise MissingSchema(\\nrequests.exceptions.MissingSchema: Invalid URL \'10.179.18.196/data/upload/1/50b124ab-0002.jpg\': No scheme supplied. Perhaps you meant https://10.179.18.196/data/upload/1/50b124ab-0002.jpg?\\n"},"status":500}\n'
```

This missing scheme looks like a bug: I'm not sure where, as a user, I am supposed to supply a scheme.

**Comment by niklub** [comment]
Thanks. We added the mention to include scheme prefix in doc https://github.com/HumanSignal/label-studio/pull/5815/files#diff-c0b883c3784a35e59bf492d3b94730d29ac02c7bfbe7ffeaac35e1cb29f150e4R190
