### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Rich-Bao** [HumanSignal/label-studio-ml-backend#446]
hi , some questions had been found when i used this  command。'pip install -e .'

![question](https://github.com/HumanSignal/label-studio-ml-backend/assets/65217096/bee0d023-e792-4e31-9413-2f2a932a9bad)

I guess it's here

![222222222222](https://github.com/HumanSignal/label-studio-ml-backend/assets/65217096/3bfcdf2f-a90f-4a15-8ab9-dc7bacb44bb0)
![111111](https://github.com/HumanSignal/label-studio-ml-backend/assets/65217096/6f10e511-f518-431d-b072-cde525f67f4e)

**Comment by RelaxingCoyote** [comment]
Hello, I'm also experiencing the same issue. Have you found a quick fix or any temporary workaround that you could share?

**Comment by ricdodds** [comment]
Same issue ☝️

**Comment by Rich-Bao** [comment]
has been resolved ，好用爱用。

**Comment by makseq** [comment]
Closed as a non-active issue, and it seems like it has been resolved.
