### ISSUE TITLE
Grounding Dino docker build issue

### ISSUE THREAD

**Issue by maaxlong** [HumanSignal/label-studio-ml-backend#462]
Hello,

I am getting the following error while trying to build Grounding Dino backend:

73.17   Downloading label_studio_converter-0.0.55-py3-none-any.whl.metadata (8.7 kB)
73.18 ERROR: Cannot install label-studio-ml 2.0.1.dev0 (from git+https://github.com/HumanSignal/label-studio-ml-backend.git) and label-studio-ml==2.0.0.dev0 because these package versions have conflicting dependencies.
73.18 
73.18 The conflict is caused by:
73.18     The user requested label-studio-ml 2.0.1.dev0 (from git+https://github.com/HumanSignal/label-studio-ml-backend.git)
73.18     The user requested label-studio-ml==2.0.0.dev0

This is on a Macbook. I have previously installed and run the Tesseract backend, and using a venv for good measure. Any suggestions?

**Comment by william9x** [comment]
I'm facing the same issue when building Dockerfile. Have to change requirements.txt  to
label-studio-converter>=0.0.55
label-studio-ml>=2.0.0.dev0
label-studio-tools>=0.0.3

**Comment by niklub** [comment]
Hello, team. Have you tried to install from the latest master? the `requirements.txt` were recently updated to 
```
label-studio-ml @ git+https://github.com/HumanSignal/label-studio-ml-backend.git@master
label_studio_converter==0.0.58
```
Let me know if it still causes the issue with build, otherwise we can mark the issue as resolved.

**Comment by niklub** [comment]
Hello guys @william9x @maaxlong !
Do you still see the issue with GroundingDINO docker build? or shall we close the issue?
