### ISSUE TITLE
Hello. I implement pre-labeling in the custom back-end model. If the predicted label category is not the label set in the front end, how can I add the predicted category to the front end label interface

### ISSUE THREAD

**Issue by MMa321** [HumanSignal/label-studio-ml-backend#464]

**Comment by niklub** [comment]
Hello. Typically you modify custom labeling configuration in Label Studio, as described here https://labelstud.io/guide/setup#Modify-the-labeling-interface

Are there any specifics in your question that are not covered by the documentation guide?

**Comment by MMa321** [comment]
> 你好。通常，您可以在 Label Studio 中修改自定义标签配置，如此处所述 https://labelstud.io/guide/setup#Modify-the-labeling-interface
> 
> 您的问题中是否有任何文档指南未涵盖的细节？

Thanks for your help, my problem has been solved！
