### ISSUE TITLE
Auto annotatiion feeture not working!

### ISSUE THREAD

**Issue by 4ff4n** [HumanSignal/label-studio-ml-backend#528]
Hello Folks!
I am having trouble with auto annotation feature of label-studio-ml-backend. It is unable to make the prediction and showing the following error:
 
![traceback_error](https://github.com/HumanSignal/label-studio-ml-backend/assets/12693438/c04e278f-2e54-4122-8d17-4e74a2b3d4ca)

Although my images upload successfully,  
![image](https://github.com/HumanSignal/label-studio-ml-backend/assets/12693438/ef23f7b6-7223-45b7-9d3d-565da7c5f958)
The back-end server is also green, showing connected.
 
![image](https://github.com/HumanSignal/label-studio-ml-backend/assets/12693438/a448dcf3-35dd-42e9-84f7-dc1a51cd9099)

Please Help if I am missing something
Thanks in advance!

**Comment by niklub** [comment]
Hello, @4ff4n !

The error in logs you see is coming from inability to access images uploaded in Label Studio from your GroundingDINO ML backend.
To ensure this is working without errors, please try the following:
1. Make sure you're using the latest ML backend and install it from docker. You may try to rebuild it to avoid caching old pip packages:
```
docker-compose build --no-cache
docker-compose up
```
2. [Per quickstart section](https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/examples/grounding_dino/README.md#quickstart), ensure you're set the correct parameters to access Label Studio instance and retrieve files from it:
      ```
      # Add these variables if you want to access the images stored in Label Studio
      - LABEL_STUDIO_HOST=
      - LABEL_STUDIO_ACCESS_TOKEN=
     ```

Let me know if that doesn't help.

**Comment by 4ff4n** [comment]
Thanks much @niklub, I was using the loop back localhost:8081 to access the resources for label studio server from inside  
label-studio-ml-backend docker container. But after using the actual IP address of my Host machine it worked!

**Comment by niklub** [comment]
Thanks! We also added more description about ML backend data access in Label Studio documentation https://github.com/HumanSignal/label-studio/pull/5815.
