### ISSUE TITLE
Button "start training" did not active fit in label-studio-ml-backend

### ISSUE THREAD

**Issue by g811201** [HumanSignal/label-studio-ml-backend#545]
**Describe the bug**
I use label-studio-ml backend to create a active learning loop.
I would like to train model only when I click "Start Training" button.
However, when I click the button, the ml-backend event in fit method get nothing rather than "START_TRAINING".
I'm not sure the issue belongs to label-studio or label-studio-ml, or is there any way to achieve the goal?

**To Reproduce**
1. Go to 'Project'-->'Settings'-->'Model'-->'...'
2. Click on 'Start Training'
3. ML backend log in fit method get nothing

**Screenshots**
![image](https://github.com/HumanSignal/label-studio/assets/57518425/b1202ab1-e29c-4fd1-a55c-bac9c89c2cd4)
![image](https://github.com/HumanSignal/label-studio-ml-backend/assets/57518425/42fb50fe-5d43-4441-8863-20d9e0e38308)

**Environment (please complete the following information):**
 - label-studio active on docker
 - Label Studio Version [1.12.1]
 - label-studio-ml   2.0.1.dev0

**Comment by makseq** [comment]
The problem is here:
https://github.com/HumanSignal/label-studio-ml-backend/blob/master/label_studio_ml/model.py#L70

It should be START_TRAINING. Hope we will fix it soon.

**Comment by makseq** [comment]
Fixed https://github.com/HumanSignal/label-studio-ml-backend/pull/565
