### ISSUE TITLE
different versions of label studio sdk.

### ISSUE THREAD

**Issue by hh1985** [HumanSignal/label-studio-ml-backend#564]
Hi 

I noticed the requirement of label studio sdk is `label-studio-sdk==0.0.34` in the master branch. Just wonder if this will cause any compatibility issue if I write code to deal with the UI using sdk > 1.0 and interact with the backend using sdk < 1.0. What to do if I want all parts to use label-studio-sdk > 1.0?

**Comment by makseq** [comment]
If you mix your environments for ml backend and UI, then it will cause problems, 0.0.34 and 1.0 are totally not compatible.  
However, we are planning to upgrade our ML backends to have SDK 1.0 everywhere.
