### ISSUE TITLE
SAM2 docker image not working

### ISSUE THREAD

**Issue by lovelesh** [HumanSignal/label-studio-ml-backend#601]
Hi,

I tried to build the docker image using the below command
`docker-compose up`
The docker image downloads all the necessary packages but the /app/start.sh does not execute. I have attached a snippet of the error below.
![image](https://github.com/user-attachments/assets/5357df62-e318-42d5-adc0-96d395c24559)

**Comment by Metareflektor** [comment]
@lovelesh have you tried it on a windows machine? i experienced the same problem as the start.sh file had CRLF line endings. After switching the line endings to LF and rebuild the image, it worked.

**Comment by StoneSteel27** [comment]
@Metareflektor Thanks for the tip, it worked. But do you know how to solve the issue of "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

**Comment by StoneSteel27** [comment]
@Metareflektor Do you have any resources for the steps?, it will be a great help. I'm trying to get it working from for days now

**Comment by lovelesh** [comment]
> @lovelesh have you tried it on a windows machine? i experienced the same problem as the start.sh file had CRLF line endings. After switching the line endings to LF and rebuild the image, it worked.

Thanks. It worked for SAM2 as well as YOLO examples
