### ISSUE TITLE
Tesseract ML backend - example.env file?

### ISSUE THREAD

**Issue by maaxlong** [HumanSignal/label-studio-ml-backend#606]
I can't find this file in the folder for tesseract, as described in the instructions. Am I missing something?

**Comment by mtanti** [comment]
The file was removed in this commit:
https://github.com/HumanSignal/label-studio-ml-backend/commit/22ae4d5c4ae2625beacba6523411b5984075bde8#diff-30258da2bbd74a7df2e613e95ea35a8404fc174d7e97db1246e91da683f211f3

What did you do, @maaxlong?

**Comment by mtanti** [comment]
OK you just need to edit `docker-compose.yml` instead and set set `LABEL_STUDIO_HOST=` and `LABEL_STUDIO_ACCESS_TOKEN=` as instructed. If you're storing data locally then you also need to remove the `minio` section.
