### ISSUE TITLE
Can I use API-key instead of deploying a ML model?

### ISSUE THREAD

**Issue by Niemj8919** [HumanSignal/label-studio-ml-backend#616]
It seems that I have to download and deploy a machine learning model locally, and then let Label-Studio use it. Can I directly transmit the data to a LLM model (such as ChatGPT, Claude) using an API key and get the annotation results?

**Comment by EthanZoneCoding** [comment]
The model has to run through a backend, but there is a backend configuration to just forward to openai

**Comment by makseq** [comment]
In Label Studio Enterprise we have Custom Javascripts that can be injected to your labeling configuration. Using them you can run requests to LLM models directly.
