### ISSUE TITLE
label studio ml does not work correctly in the venv ([Errno 22])

### ISSUE THREAD

**Issue by tesla150600** [HumanSignal/label-studio-ml-backend#617]
I created a separate virtual environment for label studio and label studio ml.
I connected Local Storage and when I made a request to ml I first got an error with the LABEL_STUDIO_URL, after the decision I got an error LABEL_STUDIO_API_KEY, but after watching other discussions I solved them myself
came before the launch of the label studio and surrounded by label studio ml set variables through $ env: LABEL _ STUDIO _ URL = "http ://127.0.0.1: 8080" and
$env:LABEL_STUDIO_API_KEY=....
but now a new bug and I can not find useful tips in discussions
error occurs when in LS I select a separate photo and press Retrieve Predictions after which nothing happens,
and in the terminal LS ml writes the following
OSError: [Errno 22] Invalid argument: 'C:\\Users\\nolro\\AppData\\Local\\label-studio\\label-studio\\Cache\\e8111d54__?d=Fora_0205_JPG_2%5C00ccc757-63ed-47a9-b728-298cdbff0e75_0.jpg'

![зображення](https://github.com/user-attachments/assets/42e5e99a-2cfc-4472-b1ea-842eac5ce6a8)

**Comment by makseq** [comment]
which version of label-studio-sdk and label-studio-ml do you have in your venv? 
We recommend to use docker to avoid dependency problems. 

label-studio-tools is a part of [label-studio-sdk](https://github.com/HumanSignal/label-studio-sdk/tree/master/src/label_studio_sdk/_extensions/label_studio_tools) now. And your screenshot shows that it's still a separate repo, it's completely wrong.
