### ISSUE TITLE
label-studio create _wsgi.py.tmpl

### ISSUE THREAD

**Issue by aguirrejuan** [HumanSignal/label-studio-ml-backend#630]
Hi,

When running the `label-studio create` command, an error occurs related to the `wsgi.format`. The issue seems to stem from the use of single `{}` instead of `{{}}` for escaping non-formatted text.

**Comment by makseq** [comment]
Thank you for pointing us, this is a fix: https://github.com/HumanSignal/label-studio-ml-backend/pull/633
