### ISSUE TITLE
I have connected label studio with gliner model back end, while 'Start Training' in logs it shows name error: from_name

### ISSUE THREAD

**Issue by aditi092001** [HumanSignal/label-studio-ml-backend#642]
![image](https://github.com/user-attachments/assets/6e773a0c-1d32-4113-8aa9-e47fecc6c6a8)
this is inside fit function of model.py file
![image](https://github.com/user-attachments/assets/fdf6ff60-4b16-480a-8ecf-01990874d0a3)

**Comment by makseq** [comment]
Could you please try using gliner ml backend from this PR? 
https://github.com/HumanSignal/label-studio-ml-backend/pull/643

**Comment by aditi092001** [comment]
Alright !! Thank you !
