### ISSUE TITLE
connect model button missing after adding one model

### ISSUE THREAD

**Issue by victorconka** [HumanSignal/label-studio-ml-backend#672]
Hi, 
is it a normal behavior for the "connect model" button to disappear after adding the first ml model ?
I have tested adding a second model via API and it works without a problem, nevertheless the frontend button is missing. 
thanks in advance

**Comment by makseq** [comment]
Yes, it was done by design. Previously, Label Studio supported multiple models, but now it is reduced to only one.

**Comment by victorconka** [comment]
Thanks for such a prompt reply!
Is the option for the second model reserved only to the Enterprise version? Or there's a different reason to it ?
