### ISSUE TITLE
Docker compose containers quit very slowly

### ISSUE THREAD

**Issue by nk9** [HumanSignal/label-studio-ml-backend#681]
When you quit the EasyOCR example Docker compose container with Ctrl-C, you have to wait 10 seconds for the process to gracefully quit. This is because the [container lacks an init process](https://stackoverflow.com/a/62854251/1749551), so the EasyOCR process is itself running as PID 1.

Fortunately, it's very easy to fix with Docker compose's [`init`](https://docs.docker.com/reference/compose-file/services/#init) setting. With that added, the process quits in 0.1s. 100x faster!

I will submit a PR for the easyocr example, since that's the one I've tested. But this is probably an issue in all the other containers as well. I'd be happy to submit a PR making the change for all of them.

**Comment by nikitabelonogov** [comment]
Hi @nk9, thank you for contribution
